# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-21 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accession', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accession',
            name='appraisal_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
