# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_auto_20170816_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='machine_name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
