# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_organization_machine_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
