# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0004_auto_20170817_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='machine_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
