# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0008_auto_20170817_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='machine_name',
            field=models.CharField(default='orgXXX will be created here', max_length=30, unique=True),
        ),
    ]
