# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0009_auto_20170817_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='machine_user',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
