# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0010_user_machine_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='machine_user',
            field=models.CharField(blank=True, default='AUTO__GEN', max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orgs.Organization', unique=True),
        ),
    ]
