# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0012_auto_20170912_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_machine_account',
            field=models.BooleanField(default=True),
        ),
    ]
