# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0018_archives'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archives',
            old_name='machine_file',
            new_name='machine_file_path',
        ),
    ]
