# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0019_auto_20170918_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='archives',
            name='machine_file_identifier',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
