# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0020_archives_machine_file_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archives',
            name='machine_file_identifier',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
