# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0021_auto_20170918_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='archives',
            name='machine_file_type',
            field=models.CharField(choices=[('ZIP', 'zip'), ('TAR', 'tar')], default='TAR', max_length=5),
            preserve_default=False,
        ),
    ]
