# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0022_archives_machine_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archives',
            name='machine_file_type',
            field=models.CharField(choices=[('ZIP', 'zip'), ('TAR', 'tar'), ('OTHER', 'OTHER')], max_length=5),
        ),
    ]
