# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0023_auto_20170918_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='archives',
            name='bag_it_name',
            field=models.CharField(default='blue', max_length=60),
            preserve_default=False,
        ),
    ]
