# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0024_archives_bag_it_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='archives',
            name='bag_it_valid',
            field=models.BooleanField(default=False),
        ),
    ]
