# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0025_archives_bag_it_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='from_ldap',
            field=models.BooleanField(default=False, editable=False, verbose_name='LDAP user'),
        ),
    ]
