# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0026_user_from_ldap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='from_ldap',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
