# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0027_auto_20170921_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='LDapUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=10)),
                ('authorized', models.BooleanField(default=False)),
            ],
        ),
    ]
