# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0028_ldapusers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LDapUsers',
        ),
        migrations.AddField(
            model_name='user',
            name='is_new_account',
            field=models.BooleanField(default=False),
        ),
    ]
