# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 05:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0029_auto_20170929_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='machine_user',
        ),
    ]
