# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0032_auto_20171004_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baglog',
            options={'ordering': ['-created_time']},
        ),
    ]
