# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0034_user_is_org_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archives',
            options={'ordering': ['machine_file_upload_time']},
        ),
    ]
