# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0035_auto_20171009_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='archives',
            name='process_status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
