# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0036_archives_process_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_short', models.PositiveSmallIntegerField(default=0)),
                ('status_desc', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='archives',
            name='process_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.ProcessingStatus'),
        ),
    ]
