# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-22 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0036_archives_process_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='archives',
            name='additional_error_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
