# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0037_auto_20171115_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archives',
            name='organization',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='orgs.Organization'),
        ),
    ]
