# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-19 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0038_auto_20171122_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='BagInfoMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_identifier', models.CharField(max_length=256)),
                ('internal_sender_description', models.TextField()),
                ('title', models.CharField(max_length=256)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('record_type', models.CharField(max_length=30)),
                ('bagging_date', models.DateTimeField()),
                ('bag_count', models.CharField(max_length=10)),
                ('bag_group_identifier', models.CharField(max_length=256)),
                ('payload_oxum', models.CharField(max_length=20)),
                ('bagit_profile_identifier', models.URLField()),
                ('archive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orgs.Archives')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='RecordCreators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        )
    ]
