# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0038_auto_20171115_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='archives',
            name='appraisal_note',
            field=models.TextField(blank=True),
        ),
    ]
