# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-01 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0039_archives_appraisal_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archives',
            name='appraisal_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
