# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-19 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0042_auto_20171119_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baginfometadata',
            name='language',
        ),
        migrations.AddField(
            model_name='baginfometadata',
            name='language',
            field=models.ManyToManyField(blank=True, to='orgs.LanguageCode'),
        ),
        migrations.RemoveField(
            model_name='baginfometadata',
            name='record_creators',
        ),
        migrations.AddField(
            model_name='baginfometadata',
            name='record_creators',
            field=models.ManyToManyField(blank=True, to='orgs.RecordCreators'),
        ),
    ]
