# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-28 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0043_auto_20171119_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baginfometadata',
            name='archive',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orgs.Archives'),
            preserve_default=False,
        ),
    ]
