# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-15 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0044_auto_20171128_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='acquisition_type',
            field=models.CharField(blank=True, choices=[('donation', 'Donation'), ('deposit', 'Deposit'), ('transfer', 'Transfer')], max_length=25, null=True),
        ),
    ]
