# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-09 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0045_organization_acquisition_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='baglogcodes',
            name='next_action',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='archives',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='orgs.Organization'),
        ),
        migrations.AlterField(
            model_name='baginfometadata',
            name='archive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='orgs.Archives'),
        ),
        migrations.AlterField(
            model_name='baglog',
            name='archive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='orgs.Archives'),
        ),
        migrations.AlterField(
            model_name='baglogcodes',
            name='code_type',
            field=models.CharField(choices=[('BE', 'Bag Error'), ('GE', 'General Error'), ('I', 'Info'), ('S', 'Success')], max_length=15),
        ),
    ]
