# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-27 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0046_auto_20180209_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baginfometadata',
            name='archive',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='orgs.Archives'),
        ),
    ]
