# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-03 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0048_auto_20171229_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagitprofile',
            name='bagit_profile_identifier',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='bagitprofile',
            name='version',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
    ]
