# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-28 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0048_auto_20180313_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptBagItVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='AcceptSerialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('application/zip', 'application/zip'), ('application/x-tar', 'application/x-tar'), ('application/x-gzip', 'application/x-gzip')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='BagItProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_descripton', models.TextField(blank=True)),
                ('version', models.DecimalField(decimal_places=1, default=0.1, max_digits=4)),
                ('bagit_profile_identifier', models.URLField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('allow_fetch', models.BooleanField(default=False)),
                ('serialization', models.CharField(choices=[('forbidden', 'forbidden'), ('required', 'required'), ('optional', 'optional')], default='optional', max_length=25)),
                ('applies_to_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applies_to_organization', to='orgs.Organization')),
                ('source_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_organization', to='orgs.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='BagItProfileBagInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('source_organization', 'Source-Organization'), ('organization_address', 'Organization-Address'), ('contact_name', 'Contact-Name'), ('contact_phone', 'Contact-Phone'), ('contact_email', 'Contact-Email'), ('external_descripton', 'External-Description'), ('external_identifier', 'External-Identifier'), ('internal_sender_description', 'Internal-Sender-Description'), ('internal_sender_identifier', 'Internal-Sender-Identifier'), ('title', 'Title'), ('date_start', 'Date-Start'), ('date_end', 'Date-End'), ('record_creators', 'Record-Creators'), ('record_type', 'Record-Type'), ('language', 'Language'), ('bagging_date', 'Bagging-Date'), ('bag_group_identifier', 'Bag-Group-Identifier'), ('bag_count', 'Bag-Count'), ('bag_size', 'Bag-Size'), ('payload_oxum', 'Payload-Oxum')], max_length=100)),
                ('required', models.NullBooleanField(default=False)),
                ('repeatable', models.NullBooleanField(default=True)),
                ('bag_it_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.BagItProfile')),
            ],
        ),
        migrations.CreateModel(
            name='BagItProfileBagInfoValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.CharField(max_length=256)),
                ('bagit_profile_baginfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.BagItProfileBagInfo')),
            ],
        ),
        migrations.CreateModel(
            name='ManifestsRequired',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('sha256', 'sha256'), ('md5', 'md5')], max_length=20)),
                ('bagit_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.BagItProfile')),
            ],
        ),
        migrations.CreateModel(
            name='TagFilesRequired',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('bagit_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.BagItProfile')),
            ],
        ),
        migrations.CreateModel(
            name='TagManifestsRequired',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('sha256', 'sha256'), ('md5', 'md5')], max_length=20)),
                ('bagit_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.BagItProfile')),
            ],
        ),
        migrations.AddField(
            model_name='acceptserialization',
            name='bagit_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.BagItProfile'),
        ),
        migrations.AddField(
            model_name='acceptbagitversion',
            name='bagit_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.BagItProfile'),
        ),
    ]
