# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-28 21:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0049_auto_20171228_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bagitprofilebaginfo',
            old_name='bag_it_profile',
            new_name='bagit_profile',
        ),
    ]
