# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-16 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0050_auto_20180313_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('accession_number', models.CharField(max_length=10)),
                ('accession_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('extent_files', models.PositiveIntegerField()),
                ('extent_size', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('access_restrictions', models.TextField()),
                ('use_restrictions', models.TextField()),
                ('resource', models.URLField()),
                ('acquisition_type', models.CharField(max_length=200)),
                ('appraisal_note', models.TextField(blank=True, null=True)),
                ('creators', models.ManyToManyField(to='orgs.RecordCreators')),
            ],
        ),
    ]
