# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-04 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0052_auto_20180103_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptbagitversion',
            name='name',
            field=models.CharField(choices=[('0.96', '0.96'), ('0.97', '0.97')], max_length=5),
        ),
    ]
