# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-26 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0053_auto_20180104_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bagitprofilebaginfovalues',
            old_name='values',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='acceptserialization',
            name='bagit_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accept_serialization', to='orgs.BagItProfile'),
        ),
        migrations.AlterField(
            model_name='manifestsrequired',
            name='bagit_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifests_required', to='orgs.BagItProfile'),
        ),
    ]
