# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-13 19:04
from __future__ import unicode_literals

from django.db import migrations


def add_codes(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    BAGLogCodes = apps.get_model('orgs', 'BAGLogCodes')
    if not BAGLogCodes.objects.filter(code_short='BACPT').exists():
        new_code = BAGLogCodes(
            code_short='BACPT',
            code_type='I',
            code_desc='Transfer accepted by appraisal archivist',
        ).save()
    if not BAGLogCodes.objects.filter(code_short='BREJ').exists():
        new_code = BAGLogCodes(
            code_short='BREJ',
            code_type='I',
            code_desc='Transfer rejected by appraisal archivist',
        ).save()
    if not BAGLogCodes.objects.filter(code_short='BACC').exists():
        new_code = BAGLogCodes(
            code_short='BACC',
            code_type='I',
            code_desc='Bag accessioned',
        ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0056_auto_20171221_1631'),
    ]

    operations = [
        migrations.RunPython(add_codes),
    ]
