# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-23 20:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0058_accession'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RightsStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rights_basis', models.CharField(choices=[('Copyright', 'Copyright'), ('Statute', 'Statute'), ('License', 'License'), ('Other', 'Other')], max_length=64)),
                ('accession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orgs.Accession')),
                ('applies_to_type', models.ManyToManyField(to='orgs.RecordType')),
                ('archive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orgs.Archives')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='RightsStatementCopyright',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copyright_status', models.CharField(choices=[('copyrighted', 'copyrighted'), ('public domain', 'public domain'), ('unknown', 'unknown')], default='unknown', max_length=64)),
                ('copyright_jurisdiction', models.CharField(default='us', max_length=2)),
                ('copyright_status_determination_date', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('copyright_applicable_start_date', models.DateField(blank=True, null=True)),
                ('copyright_applicable_end_date', models.DateField(blank=True, null=True)),
                ('copyright_start_date_period', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('copyright_end_date_period', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('copyright_end_date_open', models.BooleanField(default=False)),
                ('copyright_note', models.TextField()),
                ('rights_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.RightsStatement')),
            ],
        ),
        migrations.CreateModel(
            name='RightsStatementLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_terms', models.TextField(blank=True, null=True)),
                ('license_applicable_start_date', models.DateField(blank=True, null=True)),
                ('license_applicable_end_date', models.DateField(blank=True, null=True)),
                ('license_start_date_period', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('license_end_date_period', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('license_end_date_open', models.BooleanField(default=False)),
                ('license_note', models.TextField()),
                ('rights_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.RightsStatement')),
            ],
        ),
        migrations.CreateModel(
            name='RightsStatementOther',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_rights_basis', models.CharField(choices=[('Donor', 'Donor'), ('Policy', 'Policy')], max_length=64)),
                ('other_rights_applicable_start_date', models.DateField(blank=True, null=True)),
                ('other_rights_applicable_end_date', models.DateField(blank=True, null=True)),
                ('other_rights_start_date_period', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('other_rights_end_date_period', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('other_rights_end_date_open', models.BooleanField(default=False)),
                ('other_rights_note', models.TextField()),
                ('rights_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.RightsStatement')),
            ],
        ),
        migrations.CreateModel(
            name='RightsStatementRightsGranted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act', models.CharField(choices=[('publish', 'Publish'), ('disseminate', 'Disseminate'), ('replicate', 'Replicate'), ('migrate', 'Migrate'), ('modify', 'Modify'), ('use', 'Use'), ('delete', 'Delete')], max_length=64)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_date_period', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('end_date_period', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('end_date_open', models.BooleanField(default=False)),
                ('rights_granted_note', models.TextField()),
                ('restriction', models.CharField(choices=[('allow', 'Allow'), ('disallow', 'Disallow'), ('conditional', 'Conditional')], max_length=64)),
                ('rights_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.RightsStatement')),
            ],
        ),
        migrations.CreateModel(
            name='RightsStatementStatute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statute_jurisdiction', models.CharField(default='us', max_length=2)),
                ('statute_citation', models.TextField()),
                ('statute_determination_date', models.DateField(blank=True, null=True)),
                ('statute_applicable_start_date', models.DateField(blank=True, null=True)),
                ('statute_applicable_end_date', models.DateField(blank=True, null=True)),
                ('statute_start_date_period', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('statute_end_date_period', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('statute_end_date_open', models.BooleanField(default=False)),
                ('statute_note', models.TextField()),
                ('rights_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.RightsStatement')),
            ],
        ),
    ]
