# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 03:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0031_auto_20171003_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='BAGLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('archive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orgs.Archives')),
            ],
        ),
        migrations.CreateModel(
            name='BAGLogCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_type', models.CharField(choices=[('T', 'Transfer'), ('E', 'Error'), ('I', 'Info')], max_length=4)),
                ('code_desc', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='baglog',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transfer_app.BAGLogCodes'),
        ),
    ]
