# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baglogcodes',
            name='code_short',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
    ]
