# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer_app', '0002_baglogcodes_code_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='baglog',
            name='log_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
