# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer_app', '0003_baglog_log_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baglogcodes',
            name='code_type',
            field=models.CharField(choices=[('T', 'Transfer'), ('E', 'Error'), ('I', 'Info')], max_length=5),
        ),
    ]
