# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer_app', '0004_auto_20171004_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baglogcodes',
            name='code_short',
            field=models.CharField(max_length=5),
        ),
    ]
