# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 19:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer_app', '0005_auto_20171004_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baglog',
            name='archive',
        ),
        migrations.RemoveField(
            model_name='baglog',
            name='code',
        ),
        migrations.DeleteModel(
            name='BAGLog',
        ),
        migrations.DeleteModel(
            name='BAGLogCodes',
        ),
    ]
