# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-04 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0038_auto_20171122_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='RightsStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applies_to_type', models.CharField(choices=[('administrative records', 'Administrative Records'), ('annual reports', 'Annual Reports'), ('board materials', 'Board Materials'), ('communications and publications', 'Communications and Publications'), ('grant records', 'Grant Records')], max_length=100)),
                ('rights_basis', models.CharField(choices=[('Copyright', 'Copyright'), ('Statute', 'Statute'), ('License', 'License'), ('Other', 'Other')], max_length=64)),
                ('archive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orgs.Archives')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='RightsStatementCopyright',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copyright_status', models.CharField(choices=[('copyrighted', 'copyrighted'), ('public domain', 'public domain'), ('unknown', 'unknown')], default='unknown', max_length=64)),
                ('copyright_jurisdiction', models.CharField(max_length=2)),
                ('copyright_period', models.PositiveSmallIntegerField()),
                ('copyright_status_determination_date', models.DateField(blank=True, null=True)),
                ('copyright_applicable_start_date', models.DateField(blank=True, null=True)),
                ('copyright_applicable_end_date', models.DateField(blank=True, null=True)),
                ('copyright_end_date_open', models.BooleanField(default=False)),
                ('copyright_note', models.TextField()),
                ('rights_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rights.RightsStatement')),
            ],
        ),
        migrations.CreateModel(
            name='RightsStatementLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence_period', models.PositiveSmallIntegerField()),
                ('license_terms', models.TextField(blank=True, null=True)),
                ('license_applicable_start_date', models.DateField(blank=True, null=True)),
                ('license_applicable_end_date', models.DateField(blank=True, null=True)),
                ('license_end_date_open', models.BooleanField(default=False)),
                ('license_note', models.TextField()),
                ('rights_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rights.RightsStatement')),
            ],
        ),
        migrations.CreateModel(
            name='RightsStatementOther',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_rights_basis', models.CharField(choices=[('Donor', 'Donor'), ('Policy', 'Policy')], max_length=64)),
                ('other_rights_period', models.PositiveSmallIntegerField()),
                ('other_rights_applicable_start_date', models.DateField(blank=True, null=True)),
                ('other_rights_applicable_end_date', models.DateField(blank=True, null=True)),
                ('other_rights_end_date_open', models.BooleanField(default=False)),
                ('other_rights_note', models.TextField()),
                ('rightsstatement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rights.RightsStatement')),
            ],
        ),
        migrations.CreateModel(
            name='RightsStatementRightsGranted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rights_granted_period', models.PositiveSmallIntegerField()),
                ('act', models.CharField(choices=[('publish', 'Publish'), ('disseminate', 'Disseminate'), ('replicate', 'Replicate'), ('migrate', 'Migrate'), ('modify', 'Modify'), ('use', 'Use'), ('delete', 'Delete')], max_length=64)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_date_open', models.BooleanField(default=False)),
                ('rights_granted_note', models.TextField()),
                ('restriction', models.CharField(choices=[('allow', 'Allow'), ('disallow', 'Disallow'), ('conditional', 'Conditional')], max_length=64)),
                ('rights_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rights.RightsStatement')),
            ],
        ),
        migrations.CreateModel(
            name='RightsStatementStatute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statute_period', models.PositiveSmallIntegerField()),
                ('statute_jurisdiction', models.CharField(max_length=2)),
                ('statute_citation', models.TextField()),
                ('statute_determination_date', models.DateField(blank=True, null=True)),
                ('statute_applicable_start_date', models.DateField(blank=True, null=True)),
                ('statute_applicable_end_date', models.DateField(blank=True, null=True)),
                ('statute_end_date_open', models.BooleanField(default=False)),
                ('statute_note', models.TextField()),
                ('rights_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rights.RightsStatement')),
            ],
        ),
    ]
