# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-04 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rights', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rightsstatementlicense',
            old_name='licence_period',
            new_name='license_period',
        ),
        migrations.RenameField(
            model_name='rightsstatementother',
            old_name='rightsstatement',
            new_name='rights_statement',
        ),
    ]
