# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-08 04:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rights', '0002_auto_20171204_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rightsstatementcopyright',
            name='copyright_period',
        ),
        migrations.RemoveField(
            model_name='rightsstatementlicense',
            name='license_period',
        ),
        migrations.RemoveField(
            model_name='rightsstatementother',
            name='other_rights_period',
        ),
        migrations.RemoveField(
            model_name='rightsstatementrightsgranted',
            name='rights_granted_period',
        ),
        migrations.RemoveField(
            model_name='rightsstatementstatute',
            name='statute_period',
        ),
        migrations.AddField(
            model_name='rightsstatementcopyright',
            name='copyright_end_date_period',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rightsstatementcopyright',
            name='copyright_start_date_period',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rightsstatementlicense',
            name='license_end_date_period',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rightsstatementlicense',
            name='license_start_date_period',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rightsstatementother',
            name='other_rights_end_date_period',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rightsstatementother',
            name='other_rights_start_date_period',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rightsstatementrightsgranted',
            name='end_date_period',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rightsstatementrightsgranted',
            name='start_date_period',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rightsstatementstatute',
            name='statute_end_date_period',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rightsstatementstatute',
            name='statute_start_date_period',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rightsstatementcopyright',
            name='copyright_jurisdiction',
            field=models.CharField(default='us', max_length=2),
        ),
        migrations.AlterField(
            model_name='rightsstatementcopyright',
            name='copyright_status_determination_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='rightsstatementstatute',
            name='statute_jurisdiction',
            field=models.CharField(default='us', max_length=2),
        ),
    ]
