# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-05 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rights', '0003_auto_20171207_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='rightsstatement',
            name='applies_to_type',
        ),
        migrations.AddField(
            model_name='rightsstatement',
            name='applies_to_type',
            field=models.ManyToManyField(to='rights.RecordType'),
        ),
    ]
