#! /bin/bash 
#  
#  RACdeluser - Rockefeller Archive Center  Delete User 
#
#  Delete a user   
#
#  1) Verify the user exists 
#  2) Delete the user from system, not ldap.	
#
#
#  USAGE:
#    RACdeluser <user>
#	
#
#  Logging:  Output and error messages are placed in the the system log. 
#                  tail -f /var/log/messages to view output in real time
#
#
#
# ---------------------- Return Codes -------------------------
#             1 - General Fail - Operation not completed.
#             2 - No input parameters, Must have at least at least two arguments to run
#             3 - The user does not exits. 
#             4 - The Group does not exits. 
#             5 - The user is already part of a "org" group.  Only allowed in 1 Rockefeller Archive groupi
#             6 - usermod failed, see system log for return code from usermod. 
# 
#  $Id: RACdeluser,v 1.00 8/02/2017 URDB dI$
#
#
# Write a message to syslog and stderr, depending on the verboseness level
# Arguments are LEVEL MESSAGE; LEVEL is either "err" or "info".
log ()
{
  
  if [ $# -le 1 ]; then
    echo "RACdeluser: Must have at least two arguments to log()" 1>&2
    return 1
  fi
 
  FACILITY="$1"
  shift
  case "$FACILITY" in
    err|info|debug) : ;;
    *)  echo "RACdeluser: I do not recognize level '$FACILITY' " 1>&2 ;;
  esac
      logger "RACdeluser: $FACILITY:  $@"
}

 

#-------------------------------------------------MAIN---------------------------------------
#
#  Set some variabilities
#
log info "RACdeluser started at $(date)"
#
# set to 1 to turn on Debugging
#

if [ $# -lt 1 ]; then
   log err "Error, RACdeluser requires one input arguments, terminating"
   exit 2
else
   if [ $1 = "manual" ]; then
      INTERACTIVE_MODE=1
      log info "Running in Interactive Mode"
   fi
fi

#
#  -u  Treat unset variables as an error when substituting.
#
set -u


#  Verify the user exists.
if [ -z "$(getent passwd $1 )" ]; then
  log err "User $1 does not exist, terminiting."
  exit 4
fi
log info "User $1 found"

#
# Remove the user from the system.                         
#
userdel $1 
rc=$?; if [[ $rc != 0 ]]; then 
   log err "Failed to delete $1,  return code from userdel: $rc, terminating"
   exit 6
fi
log info "User $1 deleted." 

exit 0
##########################################################################################################################
