# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-24 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag_transfer', '0012_auto_20180917_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rightsstatementrightsgranted',
            name='rights_granted_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
