# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-06 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag_transfer', '0019_auto_20181203_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accession',
            name='resource',
            field=models.CharField(max_length=255),
        ),
    ]
