# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-15 02:30
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag_transfer', '0020_auto_20181205_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMonthData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month_label', models.CharField(max_length=15)),
                ('sort_date', models.PositiveIntegerField()),
                ('upload_count', models.PositiveSmallIntegerField(default=0)),
                ('upload_size', models.FloatField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bag_transfer.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='DashboardRecordTypeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('count', models.PositiveSmallIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bag_transfer.Organization')),
            ],
        ),
    ]
