# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-17 20:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bag_transfer', '0023_auto_20190120_1916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bagitprofilebaginfovalues',
            options={'ordering': ['name']},
        ),
    ]
