# Generated by Django 2.2.10 on 2020-04-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag_transfer', '0028_auto_20200427_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptbagitversion',
            name='name',
            field=models.CharField(choices=[('0.96', '0.96'), ('0.97', '0.97'), ('1.0', '1.0')], max_length=5),
        ),
    ]
