# Generated by Django 2.2.10 on 2020-06-20 20:16

from django.db import migrations


class Migration(migrations.Migration):

    def save_profile_to_org(apps, schema_editor):
        BagItProfile = apps.get_model('bag_transfer', 'BagItProfile')
        for profile in BagItProfile.objects.all():
            profile_org = profile.applies_to_organization
            profile_org.bagit_profile = profile
            profile_org.save()

    def save_org_to_profile(apps, schema_editor):
        Organization = apps.get_model('bag_transfer', 'Organization')
        for org in Organization.objects.all():
            profile = org.bagit_profile
            profile.applies_to_organization = org
            profile.save()

    dependencies = [
        ('bag_transfer', '0030_auto_20200619_1639'),
    ]

    operations = [
        migrations.RunPython(save_profile_to_org, save_org_to_profile)
    ]
