# Generated by Django 3.2.5 on 2021-07-19 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag_transfer', '0034_auto_20210706_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagitprofilebaginfo',
            name='repeatable',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='bagitprofilebaginfo',
            name='required',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='rightsstatementrightsgranted',
            name='rights_statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rights_granted', to='bag_transfer.rightsstatement'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='first name'),
        ),
    ]
