# Generated by Django 2.2.10 on 2021-07-19 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag_transfer', '0035_auto_20210719_1454'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Archives',
            new_name='Transfer',
        ),
        migrations.AlterField(
            model_name='rightsstatementrightsgranted',
            name='rights_statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rights_granted', to='bag_transfer.RightsStatement'),
        ),
    ]
