# Generated by Django 4.0.6 on 2022-08-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag_transfer', '0040_alter_transfer_additional_error_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baginfometadata',
            name='bag_group_identifier',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='baginfometadata',
            name='external_identifier',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='baginfometadata',
            name='record_type',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='baginfometadata',
            name='title',
            field=models.CharField(max_length=191),
        ),
    ]
