# Generated by Django 4.0.4 on 2022-07-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag_transfer', '0041_alter_baginfometadata_bag_group_identifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
