# Generated by Django 4.0.7 on 2022-09-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag_transfer', '0043_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='s3_access_key_id',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='s3_secret_access_key',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='s3_username',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
    ]
