# Generated by Django 4.0.7 on 2022-09-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag_transfer', '0044_organization_s3_access_key_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='user_uploaded',
        ),
        migrations.AlterField(
            model_name='organization',
            name='machine_name',
            field=models.CharField(default='org placeholder', max_length=60, unique=True),
        ),
    ]
