# Generated by Django 4.1.7 on 2023-03-01 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag_transfer', '0045_remove_transfer_user_uploaded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
