# Generated by Django 4.2.5 on 2023-11-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag_transfer', '0046_application_is_anonymous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baginfometadata',
            name='date_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='baginfometadata',
            name='date_start',
            field=models.DateField(),
        ),
    ]
