# Generated by Django 4.2.16 on 2024-11-20 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag_transfer', '0047_alter_baginfometadata_date_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagitprofile',
            name='accept_bagit_version_names',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='bagitprofile',
            name='accept_serialization_names',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='bagitprofile',
            name='manifests_allowed_names',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='bagitprofile',
            name='manifests_required_names',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='bagitprofile',
            name='tag_files_required',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bagitprofile',
            name='tag_manifests_required_names',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='tagfilesrequired',
            name='bagit_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_files', to='bag_transfer.bagitprofile'),
        ),
    ]
