# Generated by Django 4.2.5 on 2023-11-08 18:30

from django.db import migrations


def convert_datetimes(apps, schema_editor):
    """Converts datetime field data to dates"""
    BagInfoMetadata = apps.get_model("bag_transfer", "BagInfoMetadata")
    for bag_info in BagInfoMetadata.objects.all():
        bag_info.date_end = bag_info.date_end.date()
        bag_info.date_start = bag_info.date_start.date()
        bag_info.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bag_transfer', '0047_alter_baginfometadata_date_end_and_more'),
    ]

    operations = [
        migrations.RunPython(convert_datetimes)
    ]
