# Generated by Django 4.2.16 on 2024-11-20 19:03

from django.db import migrations


def move_to_ids(apps, schema_editor):
    BagItProfile = apps.get_model("bag_transfer", "BagItProfile")
    for profile in BagItProfile.objects.all():
        profile.manifests_allowed_ids = ",".join([m.name for m in profile.manifests_allowed.all()])
        profile.manifests_required_ids = ",".join([m.name for m in profile.manifests_required.all()])
        profile.accept_serialization_ids = ",".join([m.name for m in profile.accept_serialization.all()])
        profile.accept_bagit_version_ids = ",".join([m.name for m in profile.accept_bagit_version.all()])
        profile.tag_manifests_required_ids = ",".join([m.name for m in profile.tag_manifests_required.all()])
        profile.save()


def tag_files_to_text(apps, schema_editor):
    BagItProfile = apps.get_model("bag_transfer", "BagItProfile")
    for profile in BagItProfile.objects.all():
        tag_files = ",".join([t.name for t in profile.tag_files.all()])
        profile.tag_files_required = tag_files
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bag_transfer', '0048_bagitprofile_accept_bagit_version_names_and_more'),
    ]

    operations = [
        migrations.RunPython(move_to_ids),
        migrations.RunPython(tag_files_to_text),
    ]
