# Generated by Django 4.2.16 on 2024-11-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag_transfer', '0049_auto_20241120_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceptbagitversion',
            name='bagit_profile',
        ),
        migrations.RemoveField(
            model_name='acceptserialization',
            name='bagit_profile',
        ),
        migrations.RemoveField(
            model_name='manifestsallowed',
            name='bagit_profile',
        ),
        migrations.RemoveField(
            model_name='manifestsrequired',
            name='bagit_profile',
        ),
        migrations.RemoveField(
            model_name='tagfilesrequired',
            name='bagit_profile',
        ),
        migrations.RemoveField(
            model_name='tagmanifestsrequired',
            name='bagit_profile',
        ),
        migrations.AddField(
            model_name='bagitprofile',
            name='accept_bagit_version',
            field=models.ManyToManyField(blank=True, to='bag_transfer.acceptbagitversion'),
        ),
        migrations.AddField(
            model_name='bagitprofile',
            name='accept_serialization',
            field=models.ManyToManyField(blank=True, to='bag_transfer.acceptserialization'),
        ),
        migrations.AddField(
            model_name='bagitprofile',
            name='manifests_allowed',
            field=models.ManyToManyField(to='bag_transfer.manifestsallowed'),
        ),
        migrations.AddField(
            model_name='bagitprofile',
            name='manifests_required',
            field=models.ManyToManyField(blank=True, to='bag_transfer.manifestsrequired'),
        ),
        migrations.AddField(
            model_name='bagitprofile',
            name='tag_manifests_required',
            field=models.ManyToManyField(blank=True, to='bag_transfer.tagmanifestsrequired'),
        ),
    ]
