# Generated by Django 4.2.16 on 2024-11-20 19:19

from django.db import migrations


def recreate_relationships(apps, schema_editor):
    ManifestsAllowed = apps.get_model("bag_transfer", "ManifestsAllowed")
    ManifestsRequired = apps.get_model("bag_transfer", "ManifestsRequired")
    AcceptSerialization = apps.get_model("bag_transfer", "AcceptSerialization")
    AcceptBagItVersion = apps.get_model("bag_transfer", "AcceptBagItVersion")
    TagManifestsRequired = apps.get_model("bag_transfer", "TagManifestsRequired")
    BagItProfile = apps.get_model("bag_transfer", "BagItProfile")
    for model in [ManifestsAllowed, ManifestsRequired, AcceptSerialization, AcceptBagItVersion, TagManifestsRequired]:
        model.objects.all().delete()
        for choice in model.name.field.choices:
            model.objects.create(name=choice[0])

    for profile in BagItProfile.objects.all():
        for model_cls, str_attribute, m2m_attribute in [
            (ManifestsAllowed, 'manifests_allowed_names', 'manifests_allowed'),
            (ManifestsRequired, 'manifests_required_names', 'manifests_required'),
            (AcceptSerialization, 'accept_serialization_names', 'accept_serialization'),
            (AcceptBagItVersion, 'accept_bagit_version_names', 'accept_bagit_version'),
            (TagManifestsRequired, 'tag_manifests_required_names', 'tag_manifests_required'),
        ]:
            names_list = getattr(profile, str_attribute)
            if names_list:
                objects = model_cls.objects.filter(name__in=names_list.split(','))
                getattr(profile, m2m_attribute).set(objects)
                profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bag_transfer', '0050_remove_acceptbagitversion_bagit_profile_and_more'),
    ]

    operations = [
        migrations.RunPython(recreate_relationships),
    ]
