# Generated by Django 4.2.16 on 2024-11-20 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bag_transfer', '0051_auto_20241120_1419'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TagFilesRequired',
        ),
    ]
