# Generated by Django 4.2.16 on 2024-11-20 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bag_transfer', '0052_delete_tagfilesrequired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bagitprofile',
            name='accept_bagit_version_names',
        ),
        migrations.RemoveField(
            model_name='bagitprofile',
            name='accept_serialization_names',
        ),
        migrations.RemoveField(
            model_name='bagitprofile',
            name='manifests_allowed_names',
        ),
        migrations.RemoveField(
            model_name='bagitprofile',
            name='manifests_required_names',
        ),
        migrations.RemoveField(
            model_name='bagitprofile',
            name='tag_manifests_required_names',
        ),
    ]
