# Generated by Django 4.2.16 on 2025-01-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag_transfer', '0053_remove_bagitprofile_accept_bagit_version_names_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='machine_file_size',
            field=models.BigIntegerField(),
        ),
    ]
