# Generated by Django 4.2.18 on 2025-02-19 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag_transfer', '0054_alter_transfer_machine_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='accession',
            name='archivesspace_group_identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
