# Generated by Django 4.2.23 on 2025-08-28 00:07

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bag_transfer', '0056_add_bagit_profile_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardrecordtypedata',
            name='organization',
        ),
        migrations.AlterModelOptions(
            name='recordtype',
            options={'ordering': [django.db.models.functions.text.Lower('name')]},
        ),
        migrations.DeleteModel(
            name='DashboardMonthData',
        ),
        migrations.DeleteModel(
            name='DashboardRecordTypeData',
        ),
    ]
