# Generated by Django 4.2.24 on 2025-10-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag_transfer', '0057_remove_dashboardrecordtypedata_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='s3_credentials_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
