# Generated by Django 4.2.30 on 2026-09-02 18:59

from django.db import migrations

TO_ADD = (
    ('PFAIL', 'GA', "Packaging failed", None),
    ('PPASS', 'S', "Transfer packaged", None),
)


def create_baglogs(apps, schema_editor):
    BAGLogCodes = apps.get_model('bag_transfer', 'BAGLogCodes')

    for code_short, code_type, code_desc, next_action in TO_ADD:
        if not BAGLogCodes.objects.filter(code_short=code_short).exists():
            bag_log_code = BAGLogCodes(
                code_short=code_short,
                code_type=code_type,
                code_desc=code_desc,
                next_action=next_action,
            )
            bag_log_code.save()


def delete_baglogs(apps, schema_editor):
    BAGLogCodes = apps.get_model('bag_transfer', 'BAGLogCodes')
    for code_short, _, _, _ in TO_ADD:
        BAGLogCodes.objects.filter(code_short=code_short).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bag_transfer', '0058_organization_s3_credentials_updated'),
    ]

    operations = [
        migrations.RunPython(create_baglogs, delete_baglogs),
    ]
