# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-02 13:21
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import Group


def create_groups(apps, schema_editor):
    groups_to_add = ('managing_archivists', 'appraisal_archivists', 'accessioning_archivists')

    for group in codes_to_add:
        if not Group.objects.filter(name=group).exists():
            Group.objects.create(name=group)


def delete_groups(apps, schema_editor):
    for group in Group.objects.all():
        group.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bag_transfer', '0002_auto_20180425_1045'),
    ]

    operations = [
        migrations.RunPython(create_groups, delete_groups),
    ]
