# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-15 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bag_transfer', '0003_auto_20180502_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='accession',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accession', to='bag_transfer.Organization'),
        ),
    ]
