# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-16 01:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bag_transfer', '0004_accession_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractExternalIdentifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('archivesspace', 'ArchivesSpace'), ('aurora', 'Aurora'), ('archivematica', 'Archivematica'), ('fedora', 'Fedora')], max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='recordcreators',
            name='type',
            field=models.CharField(blank=True, choices=[('family', 'Family'), ('organization', 'Organization'), ('person', 'Person')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='AccessionExternalIdentifier',
            fields=[
                ('abstractexternalidentifier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bag_transfer.AbstractExternalIdentifier')),
                ('accession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifier', to='bag_transfer.Accession')),
            ],
            bases=('bag_transfer.abstractexternalidentifier',),
        ),
        migrations.CreateModel(
            name='ArchiveExternalIdentifier',
            fields=[
                ('abstractexternalidentifier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bag_transfer.AbstractExternalIdentifier')),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifier', to='bag_transfer.Archives')),
            ],
            bases=('bag_transfer.abstractexternalidentifier',),
        ),
        migrations.CreateModel(
            name='CollectionExternalIdentifier',
            fields=[
                ('abstractexternalidentifier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bag_transfer.AbstractExternalIdentifier')),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_identifier', to='bag_transfer.Archives')),
            ],
            bases=('bag_transfer.abstractexternalidentifier',),
        ),
        migrations.CreateModel(
            name='ParentExternalIdentifier',
            fields=[
                ('abstractexternalidentifier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bag_transfer.AbstractExternalIdentifier')),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_identifier', to='bag_transfer.Archives')),
            ],
            bases=('bag_transfer.abstractexternalidentifier',),
        ),
        migrations.CreateModel(
            name='RecordCreatorsExternalIdentifier',
            fields=[
                ('abstractexternalidentifier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bag_transfer.AbstractExternalIdentifier')),
                ('record_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifier', to='bag_transfer.RecordCreators')),
            ],
            bases=('bag_transfer.abstractexternalidentifier',),
        ),
    ]
