# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-26 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag_transfer', '0006_auto_20180523_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='accession',
            name='process_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, 'Accession created'), (20, 'Accession delivered to ArchivesSpace'), (30, 'Accession delivered to Archivematica')], default=10, null=True),
        ),
    ]
