# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-01 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag_transfer', '0010_archives_manifest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagitprofilebaginfo',
            name='field',
            field=models.CharField(choices=[('bag_count', 'Bag-Count'), ('bag_group_identifier', 'Bag-Group-Identifier'), ('bag_size', 'Bag-Size'), ('bagging_date', 'Bagging-Date'), ('contact_email', 'Contact-Email'), ('contact_name', 'Contact-Name'), ('contact_phone', 'Contact-Phone'), ('date_end', 'Date-End'), ('date_start', 'Date-Start'), ('external_descripton', 'External-Description'), ('external_identifier', 'External-Identifier'), ('internal_sender_description', 'Internal-Sender-Description'), ('internal_sender_identifier', 'Internal-Sender-Identifier'), ('language', 'Language'), ('organization_address', 'Organization-Address'), ('payload_oxum', 'Payload-Oxum'), ('record_creators', 'Record-Creators'), ('record_type', 'Record-Type'), ('source_organization', 'Source-Organization'), ('title', 'Title')], max_length=100),
        ),
    ]
