# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-29 03:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bag_transfer', '0012_auto_20180907_0853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recordtype',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='acceptbagitversion',
            name='bagit_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accept_bagit_version', to='bag_transfer.BagItProfile'),
        ),
        migrations.AlterField(
            model_name='bagitprofilebaginfo',
            name='bagit_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bag_info', to='bag_transfer.BagItProfile'),
        ),
        migrations.AlterField(
            model_name='tagfilesrequired',
            name='bagit_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_files_required', to='bag_transfer.BagItProfile'),
        ),
        migrations.AlterField(
            model_name='tagmanifestsrequired',
            name='bagit_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_manifests_required', to='bag_transfer.BagItProfile'),
        ),
    ]
