# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-02 00:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bag_transfer', '0013_auto_20180924_1018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recordtype',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='bagitprofile',
            old_name='external_descripton',
            new_name='external_description',
        ),
        migrations.AlterField(
            model_name='acceptbagitversion',
            name='bagit_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accept_bagit_version', to='bag_transfer.BagItProfile'),
        ),
        migrations.AlterField(
            model_name='bagitprofilebaginfo',
            name='bagit_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bag_info', to='bag_transfer.BagItProfile'),
        ),
        migrations.AlterField(
            model_name='bagitprofilebaginfo',
            name='field',
            field=models.CharField(choices=[('bag_count', 'Bag-Count'), ('bag_group_identifier', 'Bag-Group-Identifier'), ('bag_size', 'Bag-Size'), ('bagging_date', 'Bagging-Date'), ('contact_email', 'Contact-Email'), ('contact_name', 'Contact-Name'), ('contact_phone', 'Contact-Phone'), ('date_end', 'Date-End'), ('date_start', 'Date-Start'), ('external_description', 'External-Description'), ('external_identifier', 'External-Identifier'), ('internal_sender_description', 'Internal-Sender-Description'), ('internal_sender_identifier', 'Internal-Sender-Identifier'), ('language', 'Language'), ('organization_address', 'Organization-Address'), ('payload_oxum', 'Payload-Oxum'), ('record_creators', 'Record-Creators'), ('record_type', 'Record-Type'), ('source_organization', 'Source-Organization'), ('title', 'Title')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tagfilesrequired',
            name='bagit_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_files_required', to='bag_transfer.BagItProfile'),
        ),
        migrations.AlterField(
            model_name='tagmanifestsrequired',
            name='bagit_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_manifests_required', to='bag_transfer.BagItProfile'),
        ),
    ]
