# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-25 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bag_transfer', '0014_auto_20181001_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessionexternalidentifier',
            name='accession',
        ),
        migrations.RemoveField(
            model_name='archiveexternalidentifier',
            name='archive',
        ),
        migrations.RemoveField(
            model_name='collectionexternalidentifier',
            name='archive',
        ),
        migrations.RemoveField(
            model_name='parentexternalidentifier',
            name='archive',
        ),
        migrations.DeleteModel(
            name='AccessionExternalIdentifier',
        ),
        migrations.DeleteModel(
            name='ArchiveExternalIdentifier',
        ),
        migrations.DeleteModel(
            name='CollectionExternalIdentifier',
        ),
        migrations.DeleteModel(
            name='ParentExternalIdentifier',
        ),
        migrations.DeleteModel(
            name='AbstractExternalIdentifier',
        ),
    ]
