# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-04 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag_transfer', '0018_auto_20181129_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accession',
            name='process_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, 'Accession created'), (20, 'Accession delivered to queue')], default=10, null=True),
        ),
        migrations.AlterField(
            model_name='archives',
            name='process_status',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Transfer Started'), (20, 'Transfer Completed'), (30, 'Invalid'), (40, 'Validated'), (60, 'Rejected'), (70, 'Accepted'), (80, 'Accessioning Started'), (85, 'In Accession Queue'), (90, 'Accession Complete')], default=20),
        ),
    ]
