# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-21 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag_transfer', '0022_auto_20190114_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='from_ldap',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_new_account',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
