# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-12 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag_transfer', '0024_auto_20190617_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accession',
            name='extent_size',
            field=models.BigIntegerField(),
        ),
    ]
