# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-19 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag_transfer', '0025_auto_20190812_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='accession',
            name='archivesspace_identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accession',
            name='process_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, 'Accession created'), (20, 'Accession transfers delivered to queue'), (30, 'Accession record created in ArchivesSpace'), (40, 'Accession complete')], default=10, null=True),
        ),
    ]
