# Generated by Django 2.2.7 on 2020-04-27 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag_transfer', '0027_auto_20200118_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifestsrequired',
            name='name',
            field=models.CharField(choices=[('sha256', 'sha256'), ('sha512', 'sha512')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tagmanifestsrequired',
            name='name',
            field=models.CharField(choices=[('sha256', 'sha256'), ('sha512', 'sha512')], max_length=20),
        ),
        migrations.CreateModel(
            name='ManifestsAllowed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('sha256', 'sha256'), ('sha512', 'sha512')], max_length=20)),
                ('bagit_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifests_allowed', to='bag_transfer.BagItProfile')),
            ],
        ),
    ]
