# Generated by Django 2.2.7 on 2020-01-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag_transfer', '0027_auto_20200118_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baginfometadata',
            name='bag_count',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='baginfometadata',
            name='bag_group_identifier',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
