# Generated by Django 2.2.10 on 2020-05-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag_transfer', '0029_auto_20200430_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='machine_name',
            field=models.CharField(default='orgXXX will be created here', max_length=60, unique=True),
        ),
    ]
