# Generated by Django 2.2.10 on 2020-06-20 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bag_transfer', '0031_auto_20200620_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bagitprofile',
            name='applies_to_organization',
        ),
    ]
