# Generated by Django 2.2.10 on 2021-07-04 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag_transfer', '0032_remove_bagitprofile_applies_to_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archives',
            name='user_uploaded',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='bag_transfer.Organization'),
        ),
    ]
