# Generated by Django 3.2.5 on 2021-07-28 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bag_transfer', '0038_auto_20210728_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='bagit_profile',
        ),
    ]
