name: Automatic Release

on:
  push:
    branches:
      - base
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  automatic-release:
    uses: RockefellerArchiveCenter/.github/.github/workflows/automatic-release.yml@base
