name: Automatic Release

on:
  push:
    branches:
      - base
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    uses: RockefellerArchiveCenter/.github/.github/workflows/pythonpublish.yml@base
    with:
      use-manifest: true