name: update dependencies
on:

  schedule:
    - cron:  '0 0 1 * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v6.0.1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: development

      - name: Set up Python
        uses: actions/setup-python@v6.1.0
        with:
          python-version: '3.10'
          cache: pip

      - name: Install pre-commit and pip-tools
        run: pip install pre-commit pip-tools

      - name: Run pre-commit autoupdate
        run: pre-commit autoupdate

      - name: Run pip-compile
        run: pip-compile --upgrade --no-header

      - name: Run GitHub Actions Version Updater
        uses: saadmk11/github-actions-version-updater@v0.9.0
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          skip_pull_request: "true"

      - name: Create patch
        if: always()
        run: |
          git diff > changes.patch
          git apply --allow-empty "changes.patch"
      
      - name: Delete patch file
        if: always()
        run: rm -f changes.patch

      - name: Create Pull Request
        if: always()
        uses: peter-evans/create-pull-request@v8.0.0
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: dependency-updates
          title: "Dependency Updates"
          commit-message: "Scheduled dependency updates"