name: 'Check Branch'

on:
  pull_request:
    branches:
      - base

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: github.head_ref != 'development'
        run: |
          echo "ERROR: You can only merge to base from the development branch."
          exit 1