name: Python full suite (pip-compile, autoupdate, and tests) dependencies
on:
  schedule:
    - cron:  '0 0 1 * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  automatic-release:
    uses: RockefellerArchiveCenter/.github/.github/workflows/python-full-suite-dependencies.yml@base
